function legendObjects = PlotPin(Exo, Actual_Pin, shoulder_pin, shoulder_el,shoulder_sw, elbow_sw, elbow_el, bestP_3D, center_back, wrist, L0_recoil )
    %% Evaluates numbers of parameters and params per joint
    nparams = Exo.nParamsSh * round(Exo.numbconstraints(2)); 

    p = zeros(nparams+1, 4);          p_wr = bestP_3D(end-2:end);
    p(:,1) = bestP_3D( 1:nparams+1 ); p(:,2) = bestP_3D( nparams+2:nparams*2+2 );
    legendObjects = []; 

    %% Plot the pin for elevation
    for i = 1:round( p(1,1) )
    pinelevation = plot3( [ Actual_Pin.elevation(i,1), Actual_Pin.elevation(i,1) ], ...
                          [ shoulder_pin(2),           Actual_Pin.elevation(i,2) ], ...
                          [ shoulder_pin(3),           Actual_Pin.elevation(i,3) ], ...
                          'm',  'linewidth', 3, 'DisplayName', 'upperarm_{int}' ); 

    plot3( [ elbow_el(1) + (shoulder_el(1)-elbow_el(1)) * (1-p(6 + Exo.nParamsSh*(i-1),1)), Actual_Pin.elevation(i,1) ], ...
           [ elbow_el(2) + (shoulder_el(2)-elbow_el(2)) * (1-p(6 + Exo.nParamsSh*(i-1),1)), Actual_Pin.elevation(i,2) ], ...
           [ elbow_el(3) + (shoulder_el(3)-elbow_el(3)) * (1-p(6 + Exo.nParamsSh*(i-1),1)), Actual_Pin.elevation(i,3) ], ...
           'm', 'linewidth', 1 ); 
   
    scatter3( elbow_el(1) + (shoulder_el(1)-elbow_el(1)) * (1-p(6 + Exo.nParamsSh*(i-1),1)), ...
              elbow_el(2) + (shoulder_el(2)-elbow_el(2)) * (1-p(6 + Exo.nParamsSh*(i-1),1)), ...
              elbow_el(3) + (shoulder_el(3)-elbow_el(3)) * (1-p(6 + Exo.nParamsSh*(i-1),1)), 'mo' );
    
    % Recoil for the elevation
    dir_el = ([Actual_Pin.elevation(i,1), -0.15, Actual_Pin.elevation(i,3)] - center_back) /...
         norm([Actual_Pin.elevation(i,1), -0.15, Actual_Pin.elevation(i,3)] - center_back);

    L0_el = center_back + dir_el * norm([Actual_Pin.elevation(i,1), -0.15, Actual_Pin.elevation(i,3)] - center_back) * p( 9 + Exo.nParamsSh*(i-1), 1);
    
    plot3( [ L0_el(1), center_back(1) ], [ L0_el(2), center_back(2) ], ...
           [ L0_el(3), center_back(3) ], 'g',  'linewidth', 1.3 ); 
    
    scatter3(L0_el(1), L0_el(2), L0_el(3), 20, 'mo','filled');

    plot3( [ Actual_Pin.elevation(i,1),  L0_el(1) ], ...
           [ -0.15,                      L0_el(2) ], ...
           [ Actual_Pin.elevation(i,3),  L0_el(3) ], 'm',  'linewidth', 1 ); 

    plot3( [ Actual_Pin.elevation(i,1),  Actual_Pin.elevation(i,1) ], ...
           [ Actual_Pin.elevation(i,2),  -0.15 ], ...
           [ Actual_Pin.elevation(i,3),  Actual_Pin.elevation(i,3) ], 'm',  'linewidth', 1 ); 
    end
    legendObjects(end+1) = pinelevation;
    
    %% Plot the pin for swivel
    for i = 1:round( p( 1,2 ) )
    pinswivel = plot3( [ Actual_Pin.swivel(i,1), Actual_Pin.swivel(i,1) ], ...
                       [ shoulder_pin(2),        Actual_Pin.swivel(i,2) ], ...
                       [ shoulder_pin(3),        Actual_Pin.swivel(i,3) ], ...
                       'k', 'linewidth', 3, 'DisplayName', 'upperarm_{ext}' ); 

    plot3( [ elbow_sw(1) + (shoulder_sw(1)-elbow_sw(1)) * (1-p(6 + Exo.nParamsSh*(i-1),2 )),  Actual_Pin.swivel(i,1) ], ...
           [ elbow_sw(2) + (shoulder_sw(2)-elbow_sw(2)) * (1-p(6 + Exo.nParamsSh*(i-1),2 )),  Actual_Pin.swivel(i,2) ], ...
           [ elbow_sw(3) + (shoulder_sw(3)-elbow_sw(3)) * (1-p(6 + Exo.nParamsSh*(i-1),2 )),  Actual_Pin.swivel(i,3) ], ...
           'k', 'linewidth', 1 ); 

    scatter3(elbow_sw(1) + (shoulder_sw(1)-elbow_sw(1)) * (1-p(6 + Exo.nParamsSh*(i-1),2 )), ...
             elbow_sw(2) + (shoulder_sw(2)-elbow_sw(2)) * (1-p(6 + Exo.nParamsSh*(i-1),2 )), ...
             elbow_sw(3) + (shoulder_sw(3)-elbow_sw(3)) * (1-p(6 + Exo.nParamsSh*(i-1),2 )), 'ko' );   
    
    % Recoil for the swivel
    dir_sw = ([Actual_Pin.swivel(i,1), -0.15, Actual_Pin.swivel(i,3)] - center_back)/...
         norm([Actual_Pin.swivel(i,1), -0.15, Actual_Pin.swivel(i,3)] - center_back);
    
    L0_sw = center_back + dir_sw * norm([Actual_Pin.swivel(i,1), -0.15, Actual_Pin.swivel(i,3)] - center_back) * p( 9 + Exo.nParamsSh*(i-1), 2); 

    plot3( [ L0_sw(1), center_back(1) ], [ L0_sw(2), center_back(2) ], ...
           [ L0_sw(3), center_back(3) ], 'r',  'linewidth', 1.3 ); 
    
    scatter3(L0_sw(1), L0_sw(2), L0_sw(3), 20, 'ko','filled');

    plot3( [ Actual_Pin.swivel(i,1),  L0_sw(1) ], ...
           [ -0.15,                   L0_sw(2) ], ...
           [ Actual_Pin.swivel(i,3),  L0_sw(3) ], 'k',  'linewidth', 1 ); 
    
    plot3( [ Actual_Pin.swivel(i,1),  Actual_Pin.swivel(i,1) ], ...
           [ Actual_Pin.swivel(i,2),  -0.15 ], ...
           [ Actual_Pin.swivel(i,3),  Actual_Pin.swivel(i,3) ], 'k',  'linewidth', 1 ); 
    end    
    legendObjects(end+1) = pinswivel;  
    
    %% Plot the pin for wrist
    pinwrist = plot3( [ elbow_el(1) + ( shoulder_el(1)-elbow_el(1) ) * (1-p_wr(2)),  wrist(1)   ], ...
                      [ elbow_el(2) + ( shoulder_el(2)-elbow_el(2) ) * (1-p_wr(2)),  wrist(2)   ], ...
                      [ elbow_el(3) + ( shoulder_el(3)-elbow_el(3) ) * (1-p_wr(2)),  wrist(3)   ], ...
                      'c-', 'linewidth', 1, 'DisplayName', 'forearm' ); 
    
    legendObjects(end+1) = pinwrist; 

    scatter3( elbow_el(1) + ( shoulder_el(1)-elbow_el(1) ) * ( 1-p_wr(2) ), ...
              elbow_el(2) + ( shoulder_el(2)-elbow_el(2) ) * ( 1-p_wr(2) ), ...
              elbow_el(3) + ( shoulder_el(3)-elbow_el(3) ) * ( 1-p_wr(2) ), 'co' );
    
    scatter3( wrist(1), wrist(2), wrist(3), 'co' ); view(3);


end % END of the function