function [fitresult, gof] = createFit(L0, L, Force)
%CREATEFIT(L0,L,FORCE)
%  Create a fit.
%
%  Data for 'Orange_Fit' fit:
%      X Input : L0
%      Y Input : L
%      Z Output: Force
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2020 14:26:17


%% Fit: 'Orange_Fit'.
[xData, yData, zData] = prepareSurfaceData( L0, L, Force );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Orange_Fit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Orange_Fit', 'Force vs. L0, L', 'Location', 'NorthEast' );
% Label axes
xlabel L0
ylabel L
zlabel Force
grid on
view( -36.3, 18.0 );


