% ***********************************************************************
% MAIN SCRIPT TO DO THE ExoNET:
% The torque generated by the ExoNET is given by the sum of all the
% torques generated by each one of the Springs
% ***********************************************************************

% BEGIN
fprintf('\n\n\n\n MAIN SCRIPT~~\n')

disp('Choose from the menu...')
fieldType = menu('Choose a field to approximate:', ...
                 'TorqueApproximation', ...
                 'EXIT');        

setUp % set variables and plots
close all

switch fieldType
  case 1 % Torque Approximation
    [p,c,TAUs] = robustOpto(PHIs,BODY,Position,EXONET,nTries) % optimization

  otherwise
    disp('exiting...');
    close all
    
end % end switch

fprintf('\n\n\n\n END MAIN SCRIPT~~\n')

