% Program to plot Torque generated by single element ExoNET versus angle of
% point of attachment


%% Clear Workspace, Command Window, etc.
clc 
clear all
close all
%% Input Variables
L       = input('Length of arm = ') ;                                                  % Length of arm [ m ]
R       = input('Element attachment point distance from elbow joint = ') ;             % Element attachment point distance from elbow joint [ m ] 
theta   = input('Angle of elastic element attachment point relative to humerus = ') ;  % Angle of elastic element attachment point relative to humerus [ deg ]
k       = input('Spring Coefficient = ') ;                                             % Spring Coefficient of elastic element [ N / m ]
x0      = input('Resting length of elastic element = ') ;                              % Resting Length of elastic element [ m ]
x       = input('Final length of elastic element = ') ;                                % Final length of elastic element [ m ]

%% Call Function to Calculate Torque
[Phi,Tau] = ExoNET_TorqueAngle(L,R,theta,k,x0,x) ;                                     % Use function to calculate torque and extract variables

%% Plot Torque vs Input Angle of Forearm Position
figure                                                                                 % assign space for plot
plot(Phi,Tau,'.k') ;                                                                   % function to plot input variables
title('ExoNET Generated Torque vs Angular Position of Forearm') ;                      % Assign title to generated plot
xlabel('Phi [Degrees]') ;                                                              % Assign x-axis label to generated plot
ylabel('Tau [Nm]') ;                                                                   % Assign y-axis label to generated plot
