% Program to plot Torque generated by single element ExoNET versus angle of
% point of attachment

%% Clear Workspace, Command Window, etc.
clc 
clear all
close all
%% Input Variables
l1                 = input('Length of forearm = ') ;                                              % Length of forearm [ m ]          
l2                 = input('Length of upper arm = ') ;                                            % Length of upperarm [ m ]
r                  = input('Element attachment point distance from shoulder joint = ') ;          % Element attachment point distance from elbow joint [ m ] 
theta              = input('Angle of elastic element attachment point relative to forearm = ') ;  % Angle of elastic element attachment point relative to humerus [ deg ]
theta              = theta * pi / 180 ;                                                           % Angle of attachment point of elastic element converted to [ rad ]
phi1               = ( 0:10:360 )  ;                                                               % Angles of positions of humerus relative to coronal plane [ deg ]
phi2               = ( 0:10:360 )  ;                                                               % Angles of positions of forearm relative to humerus [ deg ]
phi1               = phi1 * pi / 180 ;                                                            % Angles of positions of humerus relative to coronal plane converted to [ rad ]
phi2               = phi2 * pi / 180 ;                                                            % Angles of positions of forearm relative to humerus converted to [ rad ]      
k                  = input('Spring Coefficient = ') ;                                             % Spring Coefficient of elastic element [ N / m ]
x0                 = input('Resting length of elastic element = ') ;                              % Resting Length of elastic element [ m ]

%% Call Function to Calculate Torque
for i=1:length(phi1)
    for j=1:length(phi2)
        [Tau_Exo1,Tau_Exo2,F,t_dist] = ExoNET2_TorqueAngle(phi1(i),phi2(j),l1,l2,r,theta,k,x0);
        f(i,j)=Tau_Exo1;
    end
end

phi1              = phi1 * 180 / pi ;                                                             % Convert angles back into [ deg ] for plotting
phi2              = phi2 * 180 / pi ;                                                             % Convert angles back into [ deg ] for plotting
%% Plot Torque vs Input Angle of Forearm Position
figure                                                                                            % Assign space for plot
surfc(phi1,phi2,f)
title('ExoNET Torque vs Angular Position of Upper Appendage (Saggital Plane)')
xlabel('Phi 1 (Humerus) [deg]');
ylabel('Phi 2 (Forearm) [deg]');